blog/urls.py
from django.urls import path 
from . import views


app_name = 'blog'

urlpatterns = [
    # post views
    path('', views.post_list, name= 'post_list'),
    #path('', views.PostListView.as_view(), name='post_list'),
    path('<int:year>/<int:month>/<int:day>/<slug:post>/',
         views.post_detail,
         name='post_detail'),
    path('<int:post_id>/',
         views.post_share, name='post_share'),
    
]

my_site/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('blog/', include('blog.urls', namespace='blog')),
]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('blog/', include('blog.urls', namespace='blog')),
]

blog/models.py
from django.db import models
from django.db.models.base import Model
from django.urls import reverse
from django.db.models.fields import CharField, SlugField, TextField
from django.utils import timezone
from django .contrib.auth.models import User
from taggit.managers import TaggableManager

class PublishedManager(models.Manager):
    def get_queryset(self):
        return super(PublishedManager,
                     self).get_queryset()\
                         .filter(status='published')

class CreationalManager(models.Manager):
    def get_queryset(self):
        return super(CreationalManager,
                     self).get_queryset()\
                     .filter(pattern='creational-pattern')

class StructuralManager(models.Manager):
    def get_queryset(self):
        return super(StructuralManager,
                     self).get_queryset()\
                     .filter(pattern='strutural-pattern')

class BehavioralManager(models.Manager):
    def get_queryset(self):
        return super(BehavioralManager,
                     self).get_queryset()\
                     .filter(pattern='behavioral-pattern')

class Post( models.Model):
    
    STATUS_CHOICES = (
        ('draft', 'Draft'),
        ('published', 'Published'),
    )
    PATTERN_CLASSIFICATION   = (
        ('creational-pattern', 'Creational Pattern'),
        ('structural-pattern', 'Structural Pattern'),
        ('behavioral-pattern', 'Behavioral Pattern')
    )

    title          =  models.TextField(max_length=150)
    tags           =  TaggableManager()
    slug           =  models.SlugField(max_length=250,
                                      unique_for_date='publish')
    author         =  models.ForeignKey(User, 
                                        on_delete=models.CASCADE,
                                        related_name='blog_posts')
    description1   =  models.TextField()
    description2   =  models.TextField()
    description3   =  models.TextField()
    intent         =  models.TextField()
    publish        =  models.DateTimeField(default=timezone.now)
    created        = models.DateTimeField(auto_now_add=True)
    updated        = models.DateTimeField(auto_now=True)
    status         = models.CharField(max_length=10,
                                      choices=STATUS_CHOICES,
                                      default='draft')
    pattern        = models.CharField(max_length=50,
                                      choices=PATTERN_CLASSIFICATION,
                                      default= 'creational-pattern') 

    objects    = models.Manager() # The default manager.
    published  = PublishedManager() # Our custom manager.
    creational = CreationalManager() # Our custom manager.
    structural = StructuralManager() # Our custom manager.
    behavioral = BehavioralManager() # Our custom manager. 
    
    class Meta:
        ordering = ('-publish',)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse("blog:post_detail", 
                        args=[self.publish.year,
                              self.publish.month,
                              self.publish.day, self.slug])

class Comment(models.Model):
    '''
    Models to Save Comments 
    '''

    post    = models.ForeignKey(Post,
                                on_delete=models.CASCADE,
                                related_name='comments')
    name    = models.CharField(max_length=150)
    email   = models.EmailField()
    body    = models.TextField()
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    active  = models.BooleanField(default=True)

    class Meta:
        db_table = 'comment'
        ordering = ('created',)
        managed = True
        verbose_name = '\comment'
        verbose_name_plural = '\comments'

    def __str__(self):
        return f'Comment by {self.name} on {self.post}'


    

blog/forms.py
from django import forms
from django.forms.fields import Field
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Submit
from django.db.models import fields
from .models import Comment

class EmailPostForm(forms.Form):
    name      = forms.CharField(max_length=25, widget=forms.TextInput(attrs={'class':'form-control'}))
    email     = forms.EmailField(widget=forms.EmailInput(attrs={'class':'form-control'}))
    to        = forms.EmailField(widget=forms.EmailInput(attrs={'class':'form-control'}))
    comments  = forms.CharField(required=False,
                                widget=forms.Textarea(attrs={'class':'form-control'}))

class CommentForm(forms.ModelForm):
    '''
    Form for the Comment section 
    '''
    def __init__(self, *args, **kwargs):
        super(CommentForm, self).__init__(*args,**kwargs)
        self.helper = FormHelper()
        self.helper.form_class = 'form-group'
        self.helper.label_class = " col-md-8"
        self.helper.field_class = "form-control "
        self.helper.form_method = "post"
        self.helper.form_action = "post_detail"

        self.helper.add_input(Submit('submit', 'Submit'))
    class Meta:
        model = Comment
        fields = ('name','email','body')
    
   
    

blog/views.py
from django.core import paginator
from django.shortcuts import render, get_object_or_404
from django.views.generic import ListView
from django.core.paginator import Paginator, EmptyPage,\
                                  PageNotAnInteger
from .forms import EmailPostForm, CommentForm
from django.core.mail import send_mail
from .models import Post, Comment
from django.db.models import Count
from taggit.models import Tag

def post_share(request, post_id):
    '''
    Forms for email 
    ''' 
    #Retrieve post by id
    post = get_object_or_404(Post, id=post_id, status='published')
    sent = False
    if request.method == 'POST':
        # Form fields passed validatation
        form = EmailPostForm(request.POST)
        if form.is_valid():
            # From fields passed validation
            cd = form.cleaned_data
            # ... send email
            post_url = request.build_absolute_uri(post.get_absolute_url())
            subject  = f"{cd['name']} recommends you read "\
                f"{post.title}"
            message  = f"Read {post.title} at {post_url}\n\n"\
                f"{cd['name']}'\s comments: {cd['comments']}"
            send_mail(subject,message, 'johnny45gotu@gmail.com', [cd['to']])
            sent = True

    else: 
        form = EmailPostForm()
    return render(request, 'blog/post/share.html', {'post': post,
                                                    'form': form,
                                                    'sent':sent})

def post_list(request, tag_slug=None):

    object_list = Post.published.all()
    tag       = None
    paginator = Paginator(object_list, 4) # 3 posts in each page
    page      = request.GET.get('page')
  
    if tag_slug:
        tag         = get_object_or_404(Tag, slug=tag_slug)
        object_list = object_list.filter(tags_in=[tag])
    paginator     = Paginator(object_list, 3) # 
    try:
        posts     = paginator.page(page)
       
    except PageNotAnInteger:
        # If page is not an integer dieliver the first page
        posts = paginator.page(1)
    except EmptyPage:
        # IF page is out of range deliver last page results
        post = paginator.page(paginator.num_pages)
   
    return render(request,
                  'blog/post/list.html',
                 {'posts':posts,
                  'page':page,
                  'tag':tag,
                  })

class PostListView(ListView):
    '''
    Here we have a generic called a ListView it will create
    '''
    queryset   = Post.published.all()
    context_object_name = 'posts'
    paginate_by = 4
    template_name = 'blog/post/list.html'

def post_detail(request, year, month, day, post):
    post = get_object_or_404(Post, slug=post,
                                   status='published',
                                   publish__year=year,
                                   publish__month=month,
                                   publish__day=day)
    
    # List of active comments for this post
    comments = post.comments.filter(active=True)

    new_comment = None
    
    if request.method == 'POST':
        # A comment was posted
        
        comment_form = CommentForm(data=request.POST)
        if comment_form.is_valid():
            # Create Comment object but don't save to database
            new_comment = comment_form.save(commit=False)
            # Assign the current post to the comment
            new_comment.post = post 
            # Save the comment to the database
            new_comment.save()
    else:
        
        comment_form = CommentForm()
    post_tags_ids = post.tags.values_list('id', flat=True)
    similar_posts = Post.published.filter(tags_in=post_tags_ids)\
                                 .exclude(id=post.id)
    similar_posts = similar_posts.annotate(same_tags=Count('tags'))\
                               .order_by('same_tags','-publish')[:4]
    return render(request,
                  'blog/post/detail.html',
                  {'post':post,
                  'comments': comments,
                  'new_comment': new_comment,
                  'comment_form': comment_form,
                  'similar_posts': similar_posts})

# Create your views here.

blog/templates/blog_main.html
{%block style%}
<style>
  .blog-header-logo {
  font-family: "https://fonts.googleapis.com/css?family=Playfair+Display:700,900" , Georgia, "Times New Roman", serif;
  font-size: 2.25rem;
}

.blog-header-logo:hover {
  text-decoration: none;
}

h1, h2, h3, h4, h5, h6 {
  font-family: "https://fonts.googleapis.com/css?family=Playfair+Display:700,900" , Georgia, "Times New Roman", serif;
}
</style>
{%endblock%}
<div class="row">
    <div class="col-md-8 blog-main">
      <h3 class="pb-3 mb-4 font-italic border-bottom">
        From the Firehose
      </h3>
    {%for post in main%}
      <div class="blog-post">
        <h2 class="blog-post-title">{{post.title}}</h2>
        <p class="blog-post-meta">{{post.publish| date:"M d, Y "}} by <a href="#">{{post.author}}</a></p>

        <p>{{post.body}}</p>
        <hr>
        <p>Cum sociis natoque penatibus et magnis <a href="#">dis parturient montes</a>, nascetur ridiculus mus. Aenean eu leo quam. Pellentesque ornare sem lacinia quam venenatis vestibulum. Sed posuere consectetur est at lobortis. Cras mattis consectetur purus sit amet fermentum.</p>
        <blockquote>
          <p>Curabitur blandit tempus porttitor. <strong>Nullam quis risus eget urna mollis</strong> ornare vel eu leo. Nullam id dolor id nibh ultricies vehicula ut id elit.</p>
        </blockquote>
        <p>Etiam porta <em>sem malesuada magna</em> mollis euismod. Cras mattis consectetur purus sit amet fermentum. Aenean lacinia bibendum nulla sed consectetur.</p>
        <h2>Heading</h2>
        <p>Vivamus sagittis lacus vel augue laoreet rutrum faucibus dolor auctor. Duis mollis, est non commodo luctus, nisi erat porttitor ligula, eget lacinia odio sem nec elit. Morbi leo risus, porta ac consectetur ac, vestibulum at eros.</p>
        <h3>Sub-heading</h3>
        <p>Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.</p>
        <pre><code>Example code block</code></pre>
        <p>Aenean lacinia bibendum nulla sed consectetur. Etiam porta sem malesuada magna mollis euismod. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa.</p>
        <h3>Sub-heading</h3>
        <p>Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Aenean lacinia bibendum nulla sed consectetur. Etiam porta sem malesuada magna mollis euismod. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus.</p>
        <ul>
          <li>Praesent commodo cursus magna, vel scelerisque nisl consectetur et.</li>
          <li>Donec id elit non mi porta gravida at eget metus.</li>
          <li>Nulla vitae elit libero, a pharetra augue.</li>
        </ul>
        <p>Donec ullamcorper nulla non metus auctor fringilla. Nulla vitae elit libero, a pharetra augue.</p>
        <ol>
          <li>Vestibulum id ligula porta felis euismod semper.</li>
          <li>Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.</li>
          <li>Maecenas sed diam eget risus varius blandit sit amet non magna.</li>
        </ol>
        <p>Cras mattis consectetur purus sit amet fermentum. Sed posuere consectetur est at lobortis.</p>
      </div><!-- /.blog-post -->
     
      {%endfor%}
     
      {%include "pagination.html" with page=main %}

    </div><!-- /.blog-main --> 

blog/templates/carousel.html
 
 {% load static %}
 
  <div id="myCarousel" class="carousel slide" data-ride="carousel">
    <ol class="carousel-indicators">
      <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
      <li data-target="#myCarousel" data-slide-to="1"></li>
      <li data-target="#myCarousel" data-slide-to="2"></li>
    </ol>
    <div class="carousel-inner">
      <div class="carousel-item active ">
        <img class="first-slide " src="{% static '../static/img/carousel/AdobeStock_64760659.jpeg'%}" alt="First slide">
        <div class="container">
          <div class="carousel-caption text-left">
            <h1>Example headline.</h1>
            <p>Cras justo odio, dapibus ac facilisis in, egestas eget quam. Donec id elit non mi porta gravida at eget metus. Nullam id dolor id nibh ultricies vehicula ut id elit.</p>
            <p><a class="btn btn-lg btn-primary" href="#" role="button">Sign up today</a></p>
          </div>
        </div>
      </div>
      <div class="carousel-item">
        <img class="second-slide" src="{% static '../static/img/carousel/AdobeStock_64760659.jpeg'%}" alt="Second slide">
        <div class="container">
          <div class="carousel-caption">
            <h1>Another example headline.</h1>
            <p>Cras justo odio, dapibus ac facilisis in, egestas eget quam. Donec id elit non mi porta gravida at eget metus. Nullam id dolor id nibh ultricies vehicula ut id elit.</p>
            <p><a class="btn btn-lg btn-primary" href="#" role="button">Learn more</a></p>
          </div>
        </div>
      </div>
      <div class="carousel-item">
        <img class="third-slide" src="{% static '../static/img/carousel/AdobeStock_64760659.jpeg'%}" alt="Third slide">
        <div class="container">
          <div class="carousel-caption text-right">
            <h1>One more for good measure.</h1>
            <p>Cras justo odio, dapibus ac facilisis in, egestas eget quam. Donec id elit non mi porta gravida at eget metus. Nullam id dolor id nibh ultricies vehicula ut id elit.</p>
            <p><a class="btn btn-lg btn-primary" href="#" role="button">Browse gallery</a></p>
          </div>
        </div>
      </div>
    </div>
    <a class="carousel-control-prev" href="#myCarousel" role="button" data-slide="prev">
      <span class="carousel-control-prev-icon" aria-hidden="true"></span>
      <span class="sr-only">Previous</span>
    </a>
    <a class="carousel-control-next" href="#myCarousel" role="button" data-slide="next">
      <span class="carousel-control-next-icon" aria-hidden="true"></span>
      <span class="sr-only">Next</span>
    </a>
  </div>

blog/templates/footer.html
<footer class="container">
    <p class="float-right"><a href="#">Back to top</a></p>
    <p>&copy; 2017-2018 Company, Inc. &middot; <a href="#">Privacy</a> &middot; <a href="#">Terms</a></p>
  </footer>

blog/templates/jumbotron.html
<div class="jumbotron jumbo_tron p-3 p-md-5 text-white background-tint rounded bg-dark">
    <div class="col-md-6 px-0">
      <h1 class="display-4 font-italic">{{ post.title }}</h1>
      <p class="lead my-3">{{post.description1 | truncatewords:15 | linebreaks }}</p>
      <p class="lead mb-0"><a href="#begin" class="text-white font-weight-bold">Continue reading...</a></p>
    </div>
  </div>

blog/templates/nav-scroller.html
<div class="nav-scroller py-1 mb-2">
    <nav class="nav d-flex justify-content-between">
      <a class="p-2 text-muted" href="#">Creation Patterns</a>
      <a class="p-2 text-muted" href="#">Structural Patterns</a>
      <a class="p-2 text-muted" href="#">Behavior Patterns</a>
      <a class="p-2 text-muted" href="#">UML's</a>
      <a class="p-2 text-muted" href="#">Implementation</a>
      <a class="p-2 text-muted" href="#">About</a>
      <a class="p-2 text-muted" href="#">Contact</a>
      
    </nav>
  </div>

blog/templates/navigation.html
<div class="row flex-nowrap justify-content-between align-items-center">
  <div class="col-12 text-center">
    <a class="blog-header-logo text-dark" href="{% url 'blog:post_list' %}">Welcome to Design Patterns</a>
  </div>

</div>

blog/templates/pagination.html
<nav class="blog-pagination">
  {% if page.has_previous %}
  <a class="btn btn-outline-primary" href="?page={{ page.previous_page_number }}">Previous</a>
{% endif %}
<span class="current">
  Page {{ page.number }} of {{ page.paginator.num_pages }}.
</span>
  {% if page.has_next %}
  <a class="btn btn-outline-secondary" href="?page={{ page.next_page_number }}">Next</a>
  {% endif %} 
</nav>

blog/templates/side.html
{% load blog_tags %}
 <aside class="col-md-4 blog-sidebar">
    <div class="p-3 mb-3 bg-light rounded">
      <h4 class="font-italic">My blog</h4>
      <p class="mb-0">This is my blog. I've written {% total_posts %} posts so far.</p>
      <pc lass="mb-0"> <a href="{% url "blog:post_feed" %}">Subscribe to my RSS feed</a></p>
    </div>
    
    <div class="p-3">
      <h3>Latest posts</h3>
      {% show_latest_posts 3 %}
      <h3>Most commented posts</h3>
      {% get_most_commented_posts as most_commented_posts %}
      <ul class="list-unstyled mb-0">
      {% for post in most_commented_posts %}
        <li>
          <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
        </li>
      {% endfor %}
      </ul>
    </div>

    <div class="p-3">
      <h4 class="font-italic">Elsewhere</h4>
      <ol class="list-unstyled">
        <li><a href="#">GitHub</a></li>
        <li><a href="#">Twitter</a></li>
        <li><a href="#">Facebook</a></li>
      </ol>
    </div>
  </aside><!-- /.blog-sidebar -->