blog/urls.py
from django.urls import path 
from . import views


app_name = 'blog'

urlpatterns = [
    # post views
    path('', views.post_list, name= 'post_list'),
    #path('', views.PostListView.as_view(), name='post_list'),
    path('<int:year>/<int:month>/<int:day>/<slug:post>/',
         views.post_detail,
         name='post_detail'),
    path('<int:post_id>/',
         views.post_share, name='post_share'),
    
]

my_site/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('blog/', include('blog.urls', namespace='blog')),
]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('blog/', include('blog.urls', namespace='blog')),
]

blog/models.py
from django.db import models
from django.db.models.base import Model
from django.urls import reverse
from django.db.models.fields import CharField, SlugField, TextField
from django.utils import timezone
from django .contrib.auth.models import User
from taggit.managers import TaggableManager

class PublishedManager(models.Manager):
    def get_queryset(self):
        return super(PublishedManager,
                     self).get_queryset()\
                         .filter(status='published')

class CreationalManager(models.Manager):
    def get_queryset(self):
        return super(CreationalManager,
                     self).get_queryset()\
                     .filter(pattern='creational-pattern')

class StructuralManager(models.Manager):
    def get_queryset(self):
        return super(StructuralManager,
                     self).get_queryset()\
                     .filter(pattern='strutural-pattern')

class BehavioralManager(models.Manager):
    def get_queryset(self):
        return super(BehavioralManager,
                     self).get_queryset()\
                     .filter(pattern='behavioral-pattern')

class Post( models.Model):
    
    STATUS_CHOICES = (
        ('draft', 'Draft'),
        ('published', 'Published'),
    )
    PATTERN_CLASSIFICATION   = (
        ('creational-pattern', 'Creational Pattern'),
        ('structural-pattern', 'Structural Pattern'),
        ('behavioral-pattern', 'Behavioral Pattern')
    )

    title          =  models.TextField(max_length=150)
    tags           =  TaggableManager()
    slug           =  models.SlugField(max_length=250,
                                      unique_for_date='publish')
    author         =  models.ForeignKey(User, 
                                        on_delete=models.CASCADE,
                                        related_name='blog_posts')
    description1   =  models.TextField()
    description2   =  models.TextField()
    description3   =  models.TextField()
    intent         =  models.TextField()
    publish        =  models.DateTimeField(default=timezone.now)
    created        = models.DateTimeField(auto_now_add=True)
    updated        = models.DateTimeField(auto_now=True)
    status         = models.CharField(max_length=10,
                                      choices=STATUS_CHOICES,
                                      default='draft')
    pattern        = models.CharField(max_length=50,
                                      choices=PATTERN_CLASSIFICATION,
                                      default= 'creational-pattern') 

    objects    = models.Manager() # The default manager.
    published  = PublishedManager() # Our custom manager.
    creational = CreationalManager() # Our custom manager.
    structural = StructuralManager() # Our custom manager.
    behavioral = BehavioralManager() # Our custom manager. 
    
    class Meta:
        ordering = ('-publish',)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse("blog:post_detail", 
                        args=[self.publish.year,
                              self.publish.month,
                              self.publish.day, self.slug])

class Comment(models.Model):
    '''
    Models to Save Comments 
    '''

    post    = models.ForeignKey(Post,
                                on_delete=models.CASCADE,
                                related_name='comments')
    name    = models.CharField(max_length=150)
    email   = models.EmailField()
    body    = models.TextField()
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    active  = models.BooleanField(default=True)

    class Meta:
        db_table = 'comment'
        ordering = ('created',)
        managed = True
        verbose_name = '\comment'
        verbose_name_plural = '\comments'

    def __str__(self):
        return f'Comment by {self.name} on {self.post}'


    

blog/forms.py
from django import forms
from django.forms.fields import Field
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Submit
from django.db.models import fields
from .models import Comment

class EmailPostForm(forms.Form):
    name      = forms.CharField(max_length=25, widget=forms.TextInput(attrs={'class':'form-control'}))
    email     = forms.EmailField(widget=forms.EmailInput(attrs={'class':'form-control'}))
    to        = forms.EmailField(widget=forms.EmailInput(attrs={'class':'form-control'}))
    comments  = forms.CharField(required=False,
                                widget=forms.Textarea(attrs={'class':'form-control'}))

class CommentForm(forms.ModelForm):
    '''
    Form for the Comment section 
    '''
    def __init__(self, *args, **kwargs):
        super(CommentForm, self).__init__(*args,**kwargs)
        self.helper = FormHelper()
        self.helper.form_class = 'form-group'
        self.helper.label_class = " col-md-8"
        self.helper.field_class = "form-control "
        self.helper.form_method = "post"
        self.helper.form_action = "post_detail"

        self.helper.add_input(Submit('submit', 'Submit'))
    class Meta:
        model = Comment
        fields = ('name','email','body')
    
   
    

blog/views.py
from django.core import paginator
from django.shortcuts import render, get_object_or_404
from django.views.generic import ListView
from django.core.paginator import Paginator, EmptyPage,\
                                  PageNotAnInteger
from .forms import EmailPostForm, CommentForm
from django.core.mail import send_mail
from .models import Post, Comment
from django.db.models import Count
from taggit.models import Tag

def post_share(request, post_id):
    '''
    Forms for email 
    ''' 
    #Retrieve post by id
    post = get_object_or_404(Post, id=post_id, status='published')
    sent = False
    if request.method == 'POST':
        # Form fields passed validatation
        form = EmailPostForm(request.POST)
        if form.is_valid():
            # From fields passed validation
            cd = form.cleaned_data
            # ... send email
            post_url = request.build_absolute_uri(post.get_absolute_url())
            subject  = f"{cd['name']} recommends you read "\
                f"{post.title}"
            message  = f"Read {post.title} at {post_url}\n\n"\
                f"{cd['name']}'\s comments: {cd['comments']}"
            send_mail(subject,message, 'johnny45gotu@gmail.com', [cd['to']])
            sent = True

    else: 
        form = EmailPostForm()
    return render(request, 'blog/post/share.html', {'post': post,
                                                    'form': form,
                                                    'sent':sent})

def post_list(request, tag_slug=None):

    object_list = Post.published.all()
    tag       = None
    paginator = Paginator(object_list, 4) # 3 posts in each page
    page      = request.GET.get('page')
  
    if tag_slug:
        tag         = get_object_or_404(Tag, slug=tag_slug)
        object_list = object_list.filter(tags_in=[tag])
    paginator     = Paginator(object_list, 3) # 
    try:
        posts     = paginator.page(page)
       
    except PageNotAnInteger:
        # If page is not an integer dieliver the first page
        posts = paginator.page(1)
    except EmptyPage:
        # IF page is out of range deliver last page results
        post = paginator.page(paginator.num_pages)
   
    return render(request,
                  'blog/post/list.html',
                 {'posts':posts,
                  'page':page,
                  'tag':tag,
                  })

class PostListView(ListView):
    '''
    Here we have a generic called a ListView it will create
    '''
    queryset   = Post.published.all()
    context_object_name = 'posts'
    paginate_by = 4
    template_name = 'blog/post/list.html'

def post_detail(request, year, month, day, post):
    post = get_object_or_404(Post, slug=post,
                                   status='published',
                                   publish__year=year,
                                   publish__month=month,
                                   publish__day=day)
    
    # List of active comments for this post
    comments = post.comments.filter(active=True)

    new_comment = None
    
    if request.method == 'POST':
        # A comment was posted
        
        comment_form = CommentForm(data=request.POST)
        if comment_form.is_valid():
            # Create Comment object but don't save to database
            new_comment = comment_form.save(commit=False)
            # Assign the current post to the comment
            new_comment.post = post 
            # Save the comment to the database
            new_comment.save()
    else:
        
        comment_form = CommentForm()
    post_tags_ids = post.tags.values_list('id', flat=True)
    similar_posts = Post.published.filter(tags_in=post_tags_ids)\
                                 .exclude(id=post.id)
    similar_posts = similar_posts.annotate(same_tags=Count('tags'))\
                               .order_by('same_tags','-publish')[:4]
    return render(request,
                  'blog/post/detail.html',
                  {'post':post,
                  'comments': comments,
                  'new_comment': new_comment,
                  'comment_form': comment_form,
                  'similar_posts': similar_posts})

# Create your views here.

blog/templates/blog/post/detail.html
{% extends "blog/base.html" %}
{% load crispy_forms_tags %}

{% block title %}{{ post.title }}{% endblock %}

{% block content %}
{% include "jumbotron.html" with post=post %}
<main role="main" class="container">
  <div class="row">
    <div class="col-md-8 blog-main">
      <h3 class="pb-3 mb-4 font-italic border-bottom">
        {{post.pattern | capfirst| truncatechars:11}}
      </h3>

      <div class="blog-post" id="begin">
        <h2 class="blog-post-title">{{post.title}}</h2>
        <p class="blog-post-meta">{{post.publish}} by <a href="#">{{post.author}}k</a></p>

        <p>This is about the {{post.title}} pattern</p>
        <hr>
        <h2>{{post.title | capfirst}}</h2>
        <ul>
          <li>{{post.description1}}</li>
          {% if post.description2 != 'N/A' %}
            <li>{{post.description2}}</li>                
          {% endif %}
          
          {% if post.description3 != 'N/A' %}
            <li>{{post.description3}}</li>
          {% endif %}
            
        </ul>
        
       <h2>Similar posts</h2>
       {% for post in similar_posts %}
        <p>
          <a href="{{ post.get_absolute_url }}">{{ post.tile }}</a>
        </p> 
        {% empty %}
          There are no similar posts yet.
        {% endfor %}
        <p><a href="{% url 'blog:post_share' post.id %}">
          Share this post
        </a></p>   
      </div><!-- /.blog-post -->
      {% with comments.count as total_comments %}
        <h2>
          {{total_comments}} comment{{ total_comments|pluralize }}
        </h2>
      {% endwith %}
      {% for comment in comments %}
        <div class="comment">
          <p class="info">
            Comment {{ forloop.counter }} by {{ comment.name}}
            {{ comment.created }}
          </p>
          {{ comment.body|linebreaks }}
        </div>
        {% empty %}
          <p>There are no comments yet.</p>
        {% endfor %}
        {% if new_comment %}
          <h2>Your comment has been added.</h2>
        {% else %}
          <h2>Added a new comment</h2>
          <form method="post">
            {% crispy comment_form  %}
            {% csrf_token %}
           
          </form>
        {% endif %}
{% endblock %}

blog/templates/blog/post/latest_posts.html
<ul>
{% for post in latest_posts %}
  <li>
    <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
  </li>
{% endfor %}
</ul>

blog/templates/blog/post/list.html
{% extends "blog/base.html" %}  {% load static %} 
{% block title %}My Blog {% endblock %}
{%block style%}
<style>
  .blog-header-logo {
  font-family: "https://fonts.googleapis.com/css?family=Playfair+Display:700,900" , Georgia, "Times New Roman", serif;
  font-size: 2.25rem;
}

.blog-header-logo:hover {
  text-decoration: none;
}

h1, h2, h3, h4, h5, h6 {
  font-family: "https://fonts.googleapis.com/css?family=Playfair+Display:700,900" , Georgia, "Times New Roman", serif;
}
</style>
{%endblock%}
 {% block content %}
<!--  -->
{% include "carousel.html" with posts='posts' %}
<div class="row mb-2">
  {% if tag %}
    <h2>Post tagged with "{{tag.name}}"</h2>
  {% endif %}
  {% for post in posts %}
  <div class="col-md-6">
    
    <div class="card flex-md-row mb-4 box-shadow h-md-250">
      <div class="card-body d-flex flex-column align-items-start">
        {% if post.pattern %}

        <strong class="d-inline-block mb-2 text-primary">{{ post.pattern }}</strong>

        {% endif %}
        <h3 class="mb-0">
          <a class="text-dark" href="#">{{post.title}}</a>
        </h3>
        <p class="tags">Tags:
          {% for tag in post.tags.all %}
            <a href="{% url 'blog:post_list_by_tag' tag.slug %}">
              {{tag.name}}
            </a> 
            {% if not forloop.last %}, {% endif %}
          {% endfor %}
          </p>
        <div class="mb-1 text-muted">{{ post.publish| date:"M d" }}</div>
        <p class="card-text mb-auto">
          {{ post.description1|truncatewords:5|linebreaks }}
        </p>
        <a href="{{ post.get_absolute_url }}">Continue reading</a>
      </div>
      <img
        class="card-img-right flex-auto d-none d-md-block thumb"
        src="{% static '../static/img/carousel/AdobeStock_64760659.jpeg'%}"
        alt="Card image cap"
      />
    </div>
    
  </div>
  {%endfor%}
</div>

 {% include "pagination.html" with page=page_obj %}



 
 {% endblock %}

 

blog/templates/blog/post/search.html
{% extends "blog/base.html" %}

{% block title %}Search{% endblock %}

{% block content %}
  {% if query %}
    <h1>Posts containing "{{ query }}"</h1>
    <h3>
      {% with results.count as total_results %}
          Found {{ total_results }} result{{ total_results|pluralize }}
      {% endwith %}
    </h3>
    {% for post in results %}
        <h4><a href="{{ post.get_absolute_url }}">{{ post.title }}</a></h4>
        {{ post.body|truncatewords:5 }}
    {% empty %}
      <p>There are no results for your query.</p>
    {% endfor %}
    <p><a href="{% url "blog:post_search" %}">Search again</a></p>
  {% else %}
    <h1>Search for posts</h1>
    <form action="." method="get">
      {{ form.as_p }}
      <input type="submit" value="Search">
    </form>
  {% endif %}
{% endblock %}

blog/templates/blog/post/share.html
{% extends "blog/base.html" %}


{% block title %}Share a post{% endblock %}

{% block content %}
  {% if sent %}
    <h1>E-mail successfully sent</h1>
    <p>
      "{{ post.title }}" was successfully sent to {{ form.cleaned_data.to }}.
    </p>
  {% else %}
    <h1>Share "{{ post.title }}" by e-mail</h1>
    <form action="." method="post">
      {{ form.as_p }}
      {% csrf_token %}
      <input type="submit" value="Send e-mail">
    </form>
  {% endif %}
{% endblock %}